# syntax = docker/dockerfile:1.2

FROM rust:slim-bookworm

#RUN --mount=type=cache,target=/usr/local/cargo \
#. "$CARGO_HOME/env" && \
RUN printf "\n[net]\ngit-fetch-with-cli = true\n" > "$CARGO_HOME/config.toml" && \
printf "\n[build]\njobs = 4\n\n" >> "$CARGO_HOME/config.toml" && \
cargo install cargo-c

